services:
  postgres:
    image: postgres:18
    env_file:
      - .env
    container_name: postgres18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
